# Generated by Django 2.0.5 on 2018-10-20 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(db_index=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(db_index=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
